// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.0
// source: resource/resource.proto

package resource

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Work struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Work's title.
	WorkTitle string `protobuf:"bytes,1,opt,name=work_title,json=workTitle,proto3" json:"work_title,omitempty"`
	// Image URL for the work.
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// When the work is released on.
	ReleasedOn string `protobuf:"bytes,3,opt,name=released_on,json=releasedOn,proto3" json:"released_on,omitempty"`
	// How number of episodes the work has.
	EpisodesCount int32 `protobuf:"varint,4,opt,name=episodes_count,json=episodesCount,proto3" json:"episodes_count,omitempty"`
	// ID of the work on Annict.
	AnnictWorkId string `protobuf:"bytes,5,opt,name=annict_work_id,json=annictWorkId,proto3" json:"annict_work_id,omitempty"`
	// URL which the work is provided.
	OfficialSiteUrl string `protobuf:"bytes,6,opt,name=official_site_url,json=officialSiteUrl,proto3" json:"official_site_url,omitempty"`
	// Wikipedia URL which the work is provided.
	WikipediaUrl string `protobuf:"bytes,7,opt,name=wikipedia_url,json=wikipediaUrl,proto3" json:"wikipedia_url,omitempty"`
}

func (x *Work) Reset() {
	*x = Work{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Work) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Work) ProtoMessage() {}

func (x *Work) ProtoReflect() protoreflect.Message {
	mi := &file_resource_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Work.ProtoReflect.Descriptor instead.
func (*Work) Descriptor() ([]byte, []int) {
	return file_resource_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Work) GetWorkTitle() string {
	if x != nil {
		return x.WorkTitle
	}
	return ""
}

func (x *Work) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Work) GetReleasedOn() string {
	if x != nil {
		return x.ReleasedOn
	}
	return ""
}

func (x *Work) GetEpisodesCount() int32 {
	if x != nil {
		return x.EpisodesCount
	}
	return 0
}

func (x *Work) GetAnnictWorkId() string {
	if x != nil {
		return x.AnnictWorkId
	}
	return ""
}

func (x *Work) GetOfficialSiteUrl() string {
	if x != nil {
		return x.OfficialSiteUrl
	}
	return ""
}

func (x *Work) GetWikipediaUrl() string {
	if x != nil {
		return x.WikipediaUrl
	}
	return ""
}

var File_resource_resource_proto protoreflect.FileDescriptor

var file_resource_resource_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x81, 0x02, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x1d, 0x0a, 0x0a,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x70, 0x69,
	0x73, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x24, 0x0a, 0x0e, 0x61, 0x6e, 0x6e, 0x69, 0x63, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6e, 0x6e, 0x69, 0x63, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69,
	0x61, 0x6c, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x53, 0x69, 0x74, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x69, 0x6b, 0x69, 0x70, 0x65, 0x64, 0x69, 0x61, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x69, 0x6b, 0x69, 0x70,
	0x65, 0x64, 0x69, 0x61, 0x55, 0x72, 0x6c, 0x42, 0x0a, 0x5a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_resource_proto_rawDescOnce sync.Once
	file_resource_resource_proto_rawDescData = file_resource_resource_proto_rawDesc
)

func file_resource_resource_proto_rawDescGZIP() []byte {
	file_resource_resource_proto_rawDescOnce.Do(func() {
		file_resource_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_resource_proto_rawDescData)
	})
	return file_resource_resource_proto_rawDescData
}

var file_resource_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resource_resource_proto_goTypes = []interface{}{
	(*Work)(nil), // 0: resource.Work
}
var file_resource_resource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_resource_proto_init() }
func file_resource_resource_proto_init() {
	if File_resource_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resource_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Work); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_resource_proto_goTypes,
		DependencyIndexes: file_resource_resource_proto_depIdxs,
		MessageInfos:      file_resource_resource_proto_msgTypes,
	}.Build()
	File_resource_resource_proto = out.File
	file_resource_resource_proto_rawDesc = nil
	file_resource_resource_proto_goTypes = nil
	file_resource_resource_proto_depIdxs = nil
}
